### ISSUE TITLE
not able to compile

### ISSUE THREAD

**Issue by plumped** [3ct0s/fud-backdoor#2]
Hey there, thank you for your work here!
I did everything like you showed in your videotutorial and the latest repository here but im not able to compile the exe without errors. Not with c++dev and also not with visual studio...

Any ideas? Did you missed some headers in the upload or something?

**Comment by 3ct0s** [comment]
Hey there, visual studio will give you an error saying that the string is too large. Please try to compile your code with DevC++ and let me know how it goes.

**Comment by plumped** [comment]
Thanks for your quick reply. I tried all ready as you use this tool also in the video. i got the following error:  
C:\Temp\Makefile.win [Build Error]  [../main.o] Error -1073741674 

Nothing changed from the main.ccp except the line: char b[] = {...}

**Comment by 3ct0s** [comment]
Can you please share your code here?

**Comment by plumped** [comment]
https://www.codepile.net/pile/RyKRV13w

**Comment by 3ct0s** [comment]
I tried compiling your code with DevC++ and it successfully compiled with no errors. Are you sure you are doing everything correctly and that you are not missing anything?

**Comment by plumped** [comment]
Can you give me a Version or better downloadlink which DevC++ you use for compiling?

**Comment by 3ct0s** [comment]
Of course, I downloaded DevC++ from [this](https://sourceforge.net/projects/orwelldevcpp/) link.

**Comment by plumped** [comment]
Okay it worked now, but its already get caught by AV after compiling :-(

**Comment by 3ct0s** [comment]
At some point, the antiviruses will be able to detect this backdoor. Here are some things you can do to make it undetectable again. 

You can try to change the payload type protocol and make it http or https and make sure to use another port, add gibberish C++ code on the main.cpp file and you can also try playing with the SSL certificate of the session. Here is an article that covers this: https://www.darkoperator.com/blog/2015/6/14/tip-meterpreter-ssl-certificate-validation

If this still doesn't work, I can't think of another way to make the connection undetectable since this is a meterpreter shell and they get detected quite easily.
